use chrono::{DateTime, FixedOffset};


#[derive(Default, Debug)]
pub struct RtData {
    pub name: String,
    pub code: String,
    pub now: f32,
    pub close: f32,
    pub open: f32,
    pub volume: i64,
    pub bid_volume: i64,
    pub ask_volume: i64,
    pub bid1: f32,
    pub bid1_volume: i64,
    pub bid2: f32,
    pub bid2_volume: i64,
    pub bid3: f32,
    pub bid3_volume: i64,
    pub bid4: f32,
    pub bid4_volume: i64,
    pub bid5: f32,
    pub bid5_volume: i64,
    pub ask1: f32,
    pub ask1_volume: i64,
    pub ask2: f32,
    pub ask2_volume: i64,
    pub ask3: f32,
    pub ask3_volume: i64,
    pub ask4: f32,
    pub ask4_volume: i64,
    pub ask5: f32,
    pub ask5_volume: i64,
    pub datatime: Option<DateTime<FixedOffset>>,
    pub gain_amout: f32,
    pub gain_percentage: f32,
    pub high: f32,
    pub low: f32,
    pub total_value: f64,
    pub turnover: Option<f32>,
    pub pe: Option<f32>,
    pub pb: Option<f32>,
    pub amplitude: f32,
    pub traded_market_value: Option<f32>,
    pub market_value: Option<f32>,
    pub high_limit: f32,
    pub low_limit: f32,
    pub quantity_relative_ratio: Option<f32>,
    pub entrust_different: Option<f32>,
    pub average_price: Option<f32>,
}